linters-settings:
  govet:
    check-shadowing: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/transcom/nom

linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck
  disable:
    - gosimple #deprecated https://github.com/golangci/golangci-lint/issues/357
    - unused #deprecated https://github.com/dominikh/go-tools/tree/master/cmd/unused
  fast: false

issues:
  # Disable defaults for the exclude patterns and instead list them all out
  # TODO: Slowly remove these where they make sense and fix code
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    # - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  fix: true

run:
  # which dirs to skip: they won't be analyzed;
  skip-dirs:
    - pkg/gen
  modules-download-mode: readonly
