repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: trailing-whitespace

  - repo: git://github.com/golangci/golangci-lint
    rev: v1.26.0
    hooks:
      - id: golangci-lint

  - repo: git://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md
