required = [
	"github.com/go-swagger/go-swagger/cmd/swagger",
	"github.com/namsral/flag"
	]

[[constraint]]
  name = "github.com/go-swagger/go-swagger"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
