version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: dep ensure
      - run: make
    working_directory: /go/src/github.com/transcom/nom
