/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Accounting struct {

	// Transportation Account Code - a reference to a line of accounting in the Transportation Global Edit Tables (TGET). This is the most common way to charge a move expense to the correct pool of money.  > TGET is a centralized repository that contains established transportation LOAs formatted in accordance with Service/Agency LOA requirements and associated TACs.  ## Army Army orders do not include a TAC. Instead, they provide an MDC.  > A movement designator code (MDC) provides the office of the Deputy Chief of Staff for Personnel with a record of the type of PCS travel performed by Active Army personnel. This record is used to centrally manage PCS funds.  The correct TAC can be located by looking up the MDC, move type, and Fiscal Year (corresponding to the orders issuance date) in the CROSSWALK Excel spreadsheet.  ## Navy Navy orders include TACs for PCS expenses (if moving expenses are authorized) and (sometimes) for NTS expenses. If present, the NTS TAC will have an underscore in the last column, which would ordinarily be populated with the last digit of the current FY. The Navy always wants to use the current Fiscal Year's TAC to pay NTS invoices, which can appear years after the Orders are cut. In other words, when it comes time to pay an NTS invoice, the underscore in the NTS TAC is replaced with the last digit of the current FY, and then that reconstructed TAC is used to look up the correct LOA in TGET. 
	Tac string `json:"tac,omitempty"`

	// Standard Document Number. The SDN is one way to connect money that was obligated for a specific member's move at order issuance time to expenses incurred by that member's move at invoicing time. This obviously only works if the SDN is unique to the member and to the specific set of orders.  ## Marine Corps The last four characters of the SDN should be same as the TAC.  At the time of this writing, the Marines have separate SDNs for each category of moving expenses (HHG, POV Storage, NTS, etc.), but only one of them is unique to a specific Marine - the Commercial Travel (CT) SDN. The CT SDN **is** the Orders # for the Marines. In the future, the Marines would like to include the first 15 characters of the CT SDN in any transactions with the Third Party Payment System, and for the TPPS to include this unique value with every expense in the resulting report. 
	Sdn string `json:"sdn,omitempty"`

	// The full Line Of Accounting. Use this if no TAC is supplied.
	Loa string `json:"loa,omitempty"`
}
