/*
 * my.move.mil Orders Gateway
 *
 * API to submit, amend, and cancel orders for my.move.mil.
 *
 * API version: 0.0.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// Affiliation : Military branch of service
type Affiliation string

// List of Affiliation
const (
	AIR_FORCE Affiliation = "air-force"
	ARMY Affiliation = "army"
	CIVILIAN_AGENCY Affiliation = "civilian-agency"
	COAST_GUARD Affiliation = "coast-guard"
	MARINE_CORPS Affiliation = "marine-corps"
	NAVY Affiliation = "navy"
)
