/*
 * my.move.mil Orders Gateway
 *
 * API to submit, amend, and cancel orders for my.move.mil.
 *
 * API version: 0.0.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Member struct {

	// In languages that use Western order, like English, this is the first name.
	GivenName string `json:"given-name"`

	// In languages that use Western order, like English, this is the last name. NOTE: some services lump suffixes (like Jr. or Sr.) in with the family name!
	FamilyName string `json:"family-name"`

	// Middle name or middle initial
	MiddleName string `json:"middle-name,omitempty"`

	// Jr., Sr., III, etc.
	Suffix string `json:"suffix,omitempty"`

	Affiliation *Affiliation `json:"affiliation"`

	Rank *Rank `json:"rank"`

	// If supplied, this is the preferred form of address or preferred human-readable rank. This is especially useful when a rank has multiple possible titles. For example, in the Army, an E-4 can be either a Specialist or a Corporal. In the Marine Corps, an E-8 can be either a Master Sergeant or a First Sergeant, and they do care about the distinction.  If omitted, use the default name for the rank for the provided affiliation. 
	Title string `json:"title,omitempty"`
}
