/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Member struct {

	// In languages that use Western order, like English, this is the first name.
	GivenName string `json:"givenName"`

	// In languages that use Western order, like English, this is the last name.
	FamilyName string `json:"familyName"`

	// Middle name or middle initial
	MiddleName string `json:"middleName,omitempty"`

	// Jr., Sr., III, etc.
	Suffix string `json:"suffix,omitempty"`

	Affiliation *Affiliation `json:"affiliation"`

	Rank *Rank `json:"rank"`

	// If supplied, this is the preferred form of address or preferred human-readable title. This is especially useful when a rank has multiple possible titles. For example, in the Army, an E-4 can be either a Specialist or a Corporal. In the Navy, there are dozens of possible job titles and ratings for enlisted sailors. In the Marine Corps, an E-8 can be either a Master Sergeant or a First Sergeant, and they do care about the distinction.  If omitted, MyMove will show the member the default name for the provided rank and affiliation. 
	Title string `json:"title,omitempty"`
}
