/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Orders struct {

	// Universally Unique IDentifier. Generated internally.
	Uuid string `json:"uuid,omitempty"`

	// Orders number. Supposed to be unique, but in practice uniqueness is not guaranteed for all branches of service.  # Army Typically found in the upper-left hand corner of printed orders.  # Navy Corresponds to the CT (Commercial Travel) SDN. On printed orders, this is found on the SDN line in the `------- ACCOUNTING DATA -------` section in the `PCS ACCOUNTING DATA` paragraph.  The BUPERS Orders number is not suitable, because it includes the sailor's full SSN, and the included four digit date code could repeat for a sailor if he or she gets orders exactly 10 years apart.  No-cost moves do not have a CT SDN, because they involve no travel. Without a CT SDN, USN Orders have nothing to use for the Orders number. Such Orders won't authorize any PCS expenses either, so they do not need to be submitted to this API.  # Marine Corps Corresponds to the CT (Commercial Travel) SDN. On Web Orders, the CT SDN is found in the table at the bottom, in the last column of the row that begins with \"Travel\".  No-cost moves do not have a CT SDN, because they involve no travel. Without a CT SDN, USMC Orders have nothing to use for the Orders number. Such Orders won't authorize any PCS expenses either, so they do not need to be submitted to this API.  # Air Force Corresponds to the SPECIAL ORDER NO, found in box 27 on AF Form 899.  # Coast Guard Corresponds to the Travel Order No.  # Civilian Corresponds to the Travel Authorization Number. 
	OrdersNum string `json:"ordersNum"`

	// Electronic Data Interchange Personal Identifier, AKA the 10 digit DoD ID Number of the member
	Edipi string `json:"edipi"`

	// Military Department or Civilian Agency that authorized these orders; e.g., Department of the Army, Department of the Navy, Defense Information Systems Agency (DISA), etc. The issuer is inferred by the system when the Orders are first created, based on the authenticated client certificate.
	Issuer string `json:"issuer"`

	Revisions []Revision `json:"revisions"`
}
