/*
 * my.move.mil Orders Gateway
 *
 * API to submit, amend, and cancel orders for my.move.mil.
 *
 * API version: 0.0.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Orders struct {

	// Universally Unique IDentifier. Generated internally.
	Uuid string `json:"uuid,omitempty"`

	// Orders number. Supposed to be unique, but in practice uniqueness is not guaranteed for all branches of service.  ## Army Typically found in the upper-left hand corner of printed orders.  ## Navy Corresponds to a transformation (see below) of the BUPERS Orders number, which is originally formatted as \"{Julian Day of the year (from 1 to 366)}{last digit of the year} {xxx-xx-xxxx SSN}\". It would be unique (because of the SSN), except that it's possible for a set of orders to be cut on the same day 10 years later for the same sailor, resulting in a collision.  On printed orders, this is typically the first line after \"RMKS/\".  ### Transformation Because the BUPERS Orders Number contains PII (the SSN) and could potentially not be unique (because it only allows a single digit for the year), this API expects the Orders number to be reformatted as \"{Julian day}{4 digit year} {EDIPI}\". The full 4 digit year can be found in the dateIssued field of the first revision, while the EDIPI can be copied from the edipi field.  Transforming this back to the BUPERS format can be achieved by removing the first three digits of the year field and replacing the EDIPI with the member's SSN. The SSN can be fetched using DMDC's Identity Web Services Real-time Broker Service.  ## Marine Corps Corresponds to the CT (Commercial Travel) SDN. On Web Orders, the CT SDN is found in the table at the bottom, in the last column of the row that begins with \"Travel\".  ## Air Force Corresponds to the Special Order number. On AF Form 899, the \"SPECIAL ORDERS NO\" is found in box 27.  ## Coast Guard Corresponds to the Travel Order No.  ## Civilian Corresponds to the Travel Authorization Number. 
	OrdersNum string `json:"ordersNum"`

	// Electronic Data Interchange Personal Identifier, AKA the 10 digit DoD ID Number of the member
	Edipi string `json:"edipi"`

	// Military Department or Civilian Agency that authorized these orders; e.g., Department of the Army, Department of the Navy, Defense Information Systems Agency (DISA), etc.
	IssuingAuthority string `json:"issuingAuthority"`

	Revisions []Revision `json:"revisions"`
}
