/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// Rank : DoD paygrade or rank of the service member. Some of these ranks will have identical entitlements.
type Rank string

// List of Rank
const (
	AVIATION_CADET Rank = "aviation-cadet"
	CADET Rank = "cadet"
	CIVILIAN Rank = "civilian"
	E_1 Rank = "e-1"
	E_2 Rank = "e-2"
	E_3 Rank = "e-3"
	E_4 Rank = "e-4"
	E_5 Rank = "e-5"
	E_6 Rank = "e-6"
	E_7 Rank = "e-7"
	E_8 Rank = "e-8"
	E_9 Rank = "e-9"
	MIDSHIPMAN Rank = "midshipman"
	O_1 Rank = "o-1"
	O_2 Rank = "o-2"
	O_3 Rank = "o-3"
	O_4 Rank = "o-4"
	O_5 Rank = "o-5"
	O_6 Rank = "o-6"
	O_7 Rank = "o-7"
	O_8 Rank = "o-8"
	O_9 Rank = "o-9"
	O_10 Rank = "o-10"
	W_1 Rank = "w-1"
	W_2 Rank = "w-2"
	W_3 Rank = "w-3"
	W_4 Rank = "w-4"
	W_5 Rank = "w-5"
)
