/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger
// TourType : Accompanied or Unaccompanied; i.e., are dependents authorized to accompany the service member on the move. For certain OCONUS destinations, the tour type affects the member's entitlement. Otherwise, it doesn't matter.  If omitted, assume accompanied. 
type TourType string

// List of TourType
const (
	ACCOMPANIED TourType = "accompanied"
	UNACCOMPANIED TourType = "unaccompanied"
	UNACCOMPANIED_DEPENDENTS_RESTRICTED TourType = "unaccompanied-dependents-restricted"
)
