/*
 * MyMove Orders Gateway
 *
 * API to submit, amend, and cancel orders for move.mil.
 *
 * API version: 0.0.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Information about either the losing or gaining Unit. If these are separation orders, the location information for the gaining Unit may be blank.
type Unit struct {

	// Human-readable name of the Unit.
	Name string `json:"name,omitempty"`

	// Unit Identification Code - a six character alphanumeric code that uniquely identifies each United States Department of Defense entity. Used in Army, Air Force, and Navy orders.  Note that the Navy has the habit of omitting the leading character, which is always \"N\" for them. 
	Uic string `json:"uic,omitempty"`

	// May be FPO or APO for OCONUS commands.
	City string `json:"city,omitempty"`

	// State (US). OCONUS units may not have the equivalent information available.
	Locality string `json:"locality,omitempty"`

	// ISO 3166-1 alpha-2 country code. If blank, but city and locality or postalCode are not blank, assume US
	Country string `json:"country,omitempty"`

	// In the USA, this is the ZIP Code.
	PostalCode string `json:"postalCode,omitempty"`
}
